routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'Auth\RegisterController@confirm'
]);

Auth::routes();

Route::group(['middleware' => 'RegularUser'], function () {

    Route::get('/home', 'HomeController@index');
    Route::get('/client', 'ClientController@index');
    Route::post('/client', 'ClientController@store');
    Route::get('/template', 'TemplateController@index');
    Route::post('/template', 'TemplateController@store');
    Route::get('/invoice', 'InvoiceController@index');
    Route::post('/invoice', 'InvoiceController@store');
});

Route::group(['middleware' => 'InvoiceAuth'], function () {

    Route::delete('/invoice', 'InvoiceController@destroy');
    Route::get('/invoice/{id}/edit', 'InvoiceController@edit');
    Route::put('/invoice/{id}/edit', 'InvoiceController@update');
});

Route::get('/pdf/{id}', 'PDFController@show')->middleware('PDF_preview');

Route::group(['middleware' => 'ClientAuth'], function () {

    Route::get('/client/{id}/edit', 'ClientController@edit');
    Route::put('/client/{id}/edit', 'ClientController@update');
    Route::delete('/client', 'ClientController@destroy');

});

Route::group(['middleware' => 'TemplateAuth'], function () {

    Route::get('/template/{id}/edit', 'TemplateController@edit');
    Route::put('/template/{id}/edit', 'TemplateController@update');
    Route::delete('/template', 'TemplateController@destroy');

});

Route::get('/supervise', 'HomeController@show')->middleware('OnlySupervisor');

Route::group(['middleware' => 'OnlySupervisor'], function () {
    Route::resource('users', 'UserController');
});

Route::group(['middleware' => 'OnlySupervisor'], function () {
    Route::resource('log', 'LogTimeController');
});

Route::get('/search', 'LogTimeController@searchUser')->middleware('OnlySupervisor');

Route::get('/month', 'LogTimeController@searchMonth')->middleware('OnlySupervisor');

Route::get('downloadExcel', 'LogTimeController@downloadExcel')->middleware('OnlySupervisor');;

Route::get('/text', 'TextController@edit')->name('text')->middleware('OnlySupervisor');

Route::get('update', 'TextController@update')->middleware('OnlySupervisor');

Route::get('/settings', 'LogTimeController@settings')->middleware('OnlySupervisor');

Route::get('/logs', 'LogTimeController@logTime')->middleware('OnlySupervisor');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'confirmation_hash', 'job_id', 'project'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function templates()
    {
        return $this->hasMany('App\Template');
    }

    public function clients()
    {
        return $this->hasMany('App\Client');
    }

    public function setTemplate(){
        $template = Template::createDefault();
        $template->user_id = $this->id;
        $template->save();
    }

    public function setClient(){
        $client = Client::createDefault();
        $client->user_id = $this->id;
        $client->save();
    }

    public function jobTypes() {

        return $this->belongsTo('App\JobType','job_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Invoice;
use App\JobType;
use App\LogTime;
use App\Template;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{

    public function index()
    {
        $users = User::where('status', 0)->get();

        return view('users.index', ['users' => $users]);
    }

    public function create()
    {
        $jobs = JobType::all();

        return view('users.create', compact('jobs'));
    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'email' => 'required|email|max:255|regex:/(.*)@quantox\.com/i|unique:users',
            'job_id' => 'required',
            'project' => 'required'
        ];
        $messages = [
            'name.required' => 'Obavezno polje :attribute.',
            'email.required' => 'Obavezno polje :attribute.',
            'email' => 'Email mora biti validan.',
            'email.regex' => 'Email domen mora biti "quantox.com".',
            'unique' => 'Email je vec u upotrebi.',
            'job_id.required' => 'Obavezno polje :attribute.',
            'project.required' => 'Obavezno polje :attribute.'
        ];
        $customAttributes = [
            'name' => 'ime',
            'job_id' => 'tip posla',
            'project' => 'projekat'
        ];
        $this->validate(request(), $rules, $messages, $customAttributes);

        $hash = str_random(64);
        $password = str_random(8);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $password,
            'confirmation_hash' => $hash,
            'job_id' => $request->job_id,
            'project' => $request->project,
        ]);
        $user->active = 1;
        $user->setTemplate();
        $user->setClient();
        $user->save();

        return redirect()->route('users.index')
            ->with('success', 'Korisnik je uspesno kreiran.');
    }

    public function edit($id)
    {
        $user = User::find($id);
        $jobs = JobType::all();

        return view('users.edit', compact('user', 'jobs'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $rules = [
            'name' => 'required',
            'email' => 'required',
            'job_id' => 'required',
            'project' => 'required'
        ];
        if ($user->email != $request->email) {
            $rules['email'] = 'required|email|max:255|regex:/(.*)@quantox\.com/i|unique:users';
        }
        $messages = [
            'name.required' => 'Obavezno polje :attribute.',
            'email.required' => 'Obavezno polje :attribute.',
            'email' => 'Email mora biti validan.',
            'email.regex' => 'Email domen mora biti "quantox.com".',
            'unique' => 'Email je vec u upotrebi.',
            'job_id.required' => 'Obavezno polje :attribute.',
            'project.required' => 'Obavezno polje :attribute.'
        ];
        $customAttributes = [
            'name' => 'ime',
            'job_id' => 'tip posla',
            'project' => 'projekat'
        ];
        $this->validate(request(), $rules, $messages, $customAttributes);

        $user->update($request->all());

        return redirect()->route('users.index')
            ->with('success', 'Korisnik je uspesno izmenjen.');
    }

    public function destroy($id)
    {
        $user = User::find($id);
        LogTime::where('user_id', $id)->delete();
        $template_id = Template::where('user_id', $id)->first();
        $client_id = Client::where('user_id', $id)->first();

        Invoice::whereIn('template_id', $template_id)
            ->whereIn('client_id', $client_id)
            ->delete();

        Template::where('user_id', $id)->delete();
        Client::where('user_id', $id)->delete();
        $user->delete();

        return redirect()->route('users.index')
            ->with('success', 'Korisnik je uspesno izbrisan.');
    }
}

resources/views/users/create.blade.php
@extends('layouts.layout')

@section('navigation')
    <li id="home"><a href="/supervise"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
    <li id="users"><a href="/users"><i class="glyphicon glyphicon-list"></i>Korisnici</a></li>
    <li id="log"><a href="/log"><i class="glyphicon glyphicon-time"></i> Logovanje </a></li>
    <li id="text"><a href="/text"><i class="glyphicon glyphicon-pencil"></i> Tekstovi </a></li>
    <li id="settings"><a href="/settings"><i class=" glyphicon glyphicon-cog"></i> Podesavanja </a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}">Nazad</a>
            </div>
        </div>
    </div>

    @if (count($errors) >0)
        <div class="alert alert-danger">
            <strong>Greska!</strong> Problem sa unosom.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('users.store') }}" method="POST">
        {{ csrf_field() }}
        @include('users.form')
    </form>

@endsection

@section('js')
    <script>
        var element = document.getElementById("users");
        element.classList.add("current");
    </script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.layout')

@section('navigation')
    <li id="home"><a href="/supervise"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
    <li id="users"><a href="/users"><i class="glyphicon glyphicon-list"></i>Korisnici</a></li>
    <li id="log"><a href="/log"><i class="glyphicon glyphicon-time"></i> Logovanje </a></li>
    <li id="text"><a href="/text"><i class="glyphicon glyphicon-pencil"></i> Tekstovi </a></li>
    <li id="settings"><a href="/settings"><i class=" glyphicon glyphicon-cog"></i> Podesavanja </a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}">Nazad</a>
            </div>
        </div>
    </div>

    @if(count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Greska!</strong> Problem sa unosom.<br><br>
            <ul>
                @foreach($errors->all() as $error)
                    <li>
                        {{$error}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('users.update', $user->id)}}" method="POST">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        @include('users.form')
    </form>

@endsection

@section('js')
    <script>
        var element = document.getElementById("users");
        element.classList.add("current");
    </script>
@endsection

resources/views/users/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-4">
        <div class="form-group">
            <strong>Ime i prezime:</strong>
            <input type="text" name="name" value="{{(isset($user))?$user->name:null}}" placeholder="ime i prezime"
                   class="form-control">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-4">
        <div class="form-group">
            <strong>email:</strong><br>
            <input type="text" name="email" value="{{(isset($user))?$user->email:'@quantox.com'}}" class="form-control">

        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-4">
        <div class="form-group">
            <strong>Tip posla:</strong><br>
            @if(isset($user))
                <select name="job_id">
                    @foreach($jobs as $job)
                        <option value="{{$job->id}}"
                                @if($user->job_id==$job->id) selected="selected" @endif>{{$job->name}}</option>
                    @endforeach
                </select>
            @else
                <select name="job_id">
                    @foreach($jobs as $job)
                        <option value="{{$job->id}}">{{$job->name}}</option>
                    @endforeach
                </select>
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-4">
        <div class="form-group">
            <strong>Projekat:</strong><br>
            <input type="text" name="project" value="{{(isset($user))?$user->project:null}}" placeholder="projekat"
                   class="form-control">
        </div>
    </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 text-left"><br>
    <button type="submit" class="btn btn-primary">Sacuvaj</button>
</div>

resources/views/users/index.blade.php
@extends('layouts.layout')
@section('navigation')
    <li id="home"><a href="/supervise"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
    <li id="users"><a href="/users"><i class="glyphicon glyphicon-list"></i>Korisnici</a></li>
    <li id="log"><a href="/log"><i class="glyphicon glyphicon-time"></i> Logovanje </a></li>
    <li id="text"><a href="/text"><i class="glyphicon glyphicon-pencil"></i> Tekstovi </a></li>
    <li id="settings"><a href="/settings"><i class=" glyphicon glyphicon-cog"></i> Podesavanja </a></li>
@endsection
@section('content')

    <h3>Pregled korisnika</h3>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('users.create') }}">Kreiraj novog korisnika</a>
            </div>
        </div>
    </div>
    <br>

    @if ($message=Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
    @endif

    @if ($message=Session::get('error'))
        <div class="alert alert-danger">
            <p>{{$message}}</p>
        </div>
    @endif

    <table class='table table-striped'>
        <tr>
            <th class="text-center"> Korisnik</th>
            <th class="text-center"> Status</th>
            <th class="text-center"> email</th>
            <th class="text-center"> Tip posla</th>
            <th class="text-center"> Projekat</th>
            <th class="text-center"> Opcije</th>
        </tr>
        @foreach($users as $user)
            <tr>
                <td>{{$user->name}}</td>
                <td>{{ $user->active?"Aktivan":"Nije aktivan"  }}</td>
                <td>{{$user->email}}</td>

                <td>
                    @if($user->jobTypes)
                        {{$user->jobTypes->name}}
                    @else /
                    @endif
                </td>
                <td>
                    @if($user->project)
                        {{$user->project}}
                    @else /
                    @endif
                </td>
                <td>
                    <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}">Izmeni</a>

                    <form action="{{route('users.destroy', $user->id)}}" method="POST" style="display: inline-block">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <a class="btn btn-danger">Izbrisi</a>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

@endsection

@section('js')
    <script>
        var element = document.getElementById("users");
        element.classList.add("current");
    </script>
@endsection