routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('register/verify/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'Auth\RegisterController@confirm'
]);

Auth::routes();

Route::group(['middleware' => 'RegularUser'], function () {

    Route::get('/home', 'HomeController@index');
    Route::get('/client', 'ClientController@index');
    Route::post('/client', 'ClientController@store');
    Route::get('/template', 'TemplateController@index');
    Route::post('/template', 'TemplateController@store');
    Route::get('/invoice', 'InvoiceController@index');
    Route::post('/invoice', 'InvoiceController@store');
});

Route::group(['middleware' => 'InvoiceAuth'], function () {

    Route::delete('/invoice', 'InvoiceController@destroy');
    Route::get('/invoice/{id}/edit', 'InvoiceController@edit');
    Route::put('/invoice/{id}/edit', 'InvoiceController@update');
});

Route::get('/pdf/{id}', 'PDFController@show')->middleware('PDF_preview');

Route::group(['middleware' => 'ClientAuth'], function () {

    Route::get('/client/{id}/edit', 'ClientController@edit');
    Route::put('/client/{id}/edit', 'ClientController@update');
    Route::delete('/client', 'ClientController@destroy');

});

Route::group(['middleware' => 'TemplateAuth'], function () {

    Route::get('/template/{id}/edit', 'TemplateController@edit');
    Route::put('/template/{id}/edit', 'TemplateController@update');
    Route::delete('/template', 'TemplateController@destroy');

});

Route::get('/supervise', 'HomeController@show')->middleware('OnlySupervisor');

Route::group(['middleware' => 'OnlySupervisor'], function () {
    Route::resource('users', 'UserController');
});

Route::group(['middleware' => 'OnlySupervisor'], function () {
    Route::resource('log', 'LogTimeController');
});

Route::get('/search', 'LogTimeController@searchUser')->middleware('OnlySupervisor');

Route::get('/month', 'LogTimeController@searchMonth')->middleware('OnlySupervisor');

Route::get('downloadExcel', 'LogTimeController@downloadExcel')->middleware('OnlySupervisor');;

Route::get('/text', 'TextController@edit')->name('text')->middleware('OnlySupervisor');

Route::get('update', 'TextController@update')->middleware('OnlySupervisor');

Route::get('/settings', 'LogTimeController@settings')->middleware('OnlySupervisor');

Route::get('/logs', 'LogTimeController@logTime')->middleware('OnlySupervisor');

resources/views/log/index.blade.php
@extends('layouts.layout')

@section('navigation')
    <li id="home"><a href="/supervise"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
    <li id="users"><a href="/users"><i class="glyphicon glyphicon-list"></i>Korisnici</a></li>
    <li id="log"><a href="/log"><i class="glyphicon glyphicon-time"></i> Logovanje </a></li>
    <li id="text"><a href="/text"><i class="glyphicon glyphicon-pencil"></i> Tekstovi </a></li>
    <li id="settings"><a href="/settings"><i class=" glyphicon glyphicon-cog"></i> Podesavanja </a></li>

@endsection

@section('content')

    <h3>Svi korisnici</h3>

    <div class="row">
        <div class="col-xs-12 col-sm-4">
            <strong>Pretrazi korisnike:</strong>
            <div class="form-inline">
                <input type="text" name="name" class="form-control" id="user_name">
                <button type="button" class="btn btn-info" id="search">Pretrazi</button>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-left">

        <br><br>
    </div>

    <div id="user">

        <table class='table table-striped'>
            <tr>
                <th class="text-center"> Ime i prezime</th>
            </tr>

            @foreach($users as $user)
                <tr>
                    <td><a href="{{route('log.show', $user->id)}}"> {{$user->name}}</a></td>

                </tr>
            @endforeach
        </table>
    </div>
@endsection

@section('js')
    <script type="text/javascript">
        $("button#search").click(function () {
            var name = $('#user_name').val();
            console.log(name);
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: "./search",
                type: "get",
                data: {data_name: name},
                success: function (response) {
                    $('#user').html(response);
                }
            });
        });

        var element = document.getElementById("log");
        element.classList.add("current");
    </script>
@endsection

resources/views/log/month.blade.php
<table class='table table-striped'>
    <tr>
        <th class="text-center"> Ime i prezime</th>
        <th class="text-center"> Projekat</th>
        <th class="text-center"> Datum</th>
        <th class="text-center"> Vreme</th>
        <th class="text-center"> Opis</th>
    </tr>
    @foreach($logs as $log)
        <tr>
            <td>{{$log->users->name}}</td>
            <td>{{$log->users->project}}</td>
            <td>{{$log->date}}</td>
            <td>{{($hour = floor($log->time/60))?$hour .'h':''}} {{($min = $log->time%60)?$min . 'min': ''}}</td>
            <td>{{$log->description}}</td>
        </tr>
    @endforeach
</table>

resources/views/log/search.blade.php
<table class='table table-striped'>
    <tr>
        <th class="text-center"> Ime i prezime</th>
    </tr>

    @foreach($users as $user)
        <tr>
            <td><a href="{{route('log.show', $user->id)}}"> {{$user->name}}</a></td>

        </tr>
    @endforeach
</table>

resources/views/log/settings.blade.php
@extends('layouts.layout')

@section('navigation')
    <li id="home"><a href="/supervise"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
    <li id="users"><a href="/users"><i class="glyphicon glyphicon-list"></i>Korisnici</a></li>
    <li id="log"><a href="/log"><i class="glyphicon glyphicon-time"></i> Logovanje </a></li>
    <li id="text"><a href="/text"><i class="glyphicon glyphicon-pencil"></i> Tekstovi </a></li>
    <li id="settings"><a href="/settings"><i class=" glyphicon glyphicon-cog"></i> Podesavanja </a></li>

@endsection

@section('content')

    <h3>Loguj vreme:</h3>

    <div class="row">
        <div class="col-xs-12 col-sm-4">
            <label for="date">Izaberi mesec:</label>
            <div class="form-inline">
                <input type="text" name="date" class="form-control date-picker" id="date">
                <button type="button" class="btn btn-info" id="search">Loguj</button>
            </div>
        </div>
    </div><br>

    <div id="loading" style="display: none">
        <img src="/images/loading.gif" alt="loading" style="left: auto" height="20%" width="20%"/>
        <h5>Podaci se upisuju...</h5>
    </div>

@endsection

@section('js')
    <script type="text/javascript">
        $(function () {
            $('.date-picker').datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm',
                onClose: function (dateText, inst) {
                    $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
                }
            });
        });

        $("button#search").click(function () {
            var date = $('#date').val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $("#loading").show();
            $.ajax({
                url: "/logs",
                type: "get",
                data: {data: date},
                success: function () {
                    $("#loading").hide();
                    alert("Uspesno je logovano vreme za izabrani mesec!");
                },
                error: function () {
                    alert("Greska");
                }
            });
        });

        var element = document.getElementById("settings");
        element.classList.add("current");
    </script>
@endsection

resources/views/log/show.blade.php
@extends('layouts.layout')

@section('navigation')
    <li id="home"><a href="/supervise"><i class="glyphicon glyphicon-home"></i> Dashboard</a></li>
    <li id="users"><a href="/users"><i class="glyphicon glyphicon-list"></i>Korisnici</a></li>
    <li id="log"><a href="/log"><i class="glyphicon glyphicon-time"></i> Logovanje </a></li>
    <li id="text"><a href="/text"><i class="glyphicon glyphicon-pencil"></i> Tekstovi </a></li>
    <li id="settings"><a href="/settings"><i class=" glyphicon glyphicon-cog"></i> Podesavanja </a></li>
@endsection

@section('content')

    <h3>Pregled logovanja</h3>

    @if($logs->isNotEmpty())

        <div class="row">
            <div class="col-xs-12 col-sm-4">
                <label for="date">Mesec:</label>
                <div class="form-inline">
                    <input type="text" name="date" class="form-control date-picker" id="date">
                    <button type="button" class="btn btn-info" id="search">Pretrazi</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-right">
                    <button type="button" class="btn btn-success" id="excel">Generisi timesheet</button>
                </div>
            </div>
        </div>
        <br>

        <div id="month">
            <table class='table table-striped'>
                <tr>
                    <th class="text-center"> Ime i prezime</th>
                    <th class="text-center"> Projekat</th>
                    <th class="text-center"> Datum</th>
                    <th class="text-center"> Vreme</th>
                    <th class="text-center"> Opis</th>
                </tr>

                @foreach($logs as $log)
                    <tr>
                        <td>{{$log->users->name}}</td>
                        <td>{{$log->users->project}}</td>
                        <td>{{$log->date}}</td>
                        <td>{{($hour = floor($log->time/60))?$hour .'h':''}} {{($min = $log->time%60)?$min . 'min': ''}}</td>
                        <td>{{$log->description}}</td>
                    </tr>
                    <input type="hidden" id='user_id' value="{{$log->users->id}}">
                @endforeach
            </table>
        </div>
    @else
        Logs don't exist.
    @endif
@endsection

@section('js')
    @if($logs->isNotEmpty())
        <script type="text/javascript">
            $(function () {
                $('.date-picker').datepicker({
                    changeMonth: true,
                    dateFormat: 'mm',
                    onClose: function (dateText, inst) {
                        $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
                    }
                });
            });
            $("button#search").click(function () {
                var date = $('#date').val();

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: "/month",
                    type: "get",
                    data: {data: date, user_id: '{{$log->users->id}}'},
                    success: function (response) {
                        $('#month').html(response);
                    }
                });
            });

            $("button#excel").click(function () {
                var date = $('#date').val();
                var user = '{{$log->users->id}}';
                if
                (date == '') alert('Izaberi mesec');
                else
                    window.open('/downloadExcel?user_id=' + user + '&date=' + date, '_blank');
            });

            var element = document.getElementById("log");
            element.classList.add("current");

        </script>
    @endif
@endsection